---
title: "Incidence of West Nile Virus in the State of Illinois 2005-2012"
output:
  word_document: default
  html_document: default
Group members: Nichole, Kathleen, Randy, and Jessy"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Introduction
In the past few weeks, a group of us worked together on our group project about the West Nile Virus (WNV) incidence in Illinois using an interactive map and visually interactive app presentations. WNV is a virus that is most commonly transmitted to humans by mosquito bites. Among those infected by WNV, 1 out of 5 develop a fever or other symptoms, and 1 out of 150 develop more serious symptoms, such as swollen lymph nodes. The primary goal of our project was to use epidemiological and demographic information, including age, gender, incident count, ethnicity, location, and race, to map WNV in Illinois from 2005 to 2012. Additionally, we created an app to add interactive functions through the embedded dashboard. With this app, it is possible to manipulate the data on the map by changing different parameters, such as sex, to observe whether counts were higher or lower for men or women. When all four members of our group started working on this project, we were concerned about how to delegate the tasks successfully, how to ensure that our map and app achieved the standard that would allow us to present to the rest of class, and how to incorporate more of what we learned in making the interactive map and app. This project does fit into the broader scrope of WNV research, particularly in creating the interactive tools to engage the public in the discussion of prevention and intervention of WNV.

## What have we gained from participation in this project?
When we were first assigned this project, half of us were unfamiliar with the topic and the importance of epidemiology, in general, since we all come from different fields of research. To note, both Nichole and Randy are MPH- Epidemiology students. Conducting a search of epidemiological data on WNV exposed us to more information about this virus and its effect on the human population. That gave us a better understanding of the importance of developing this interactive app and providing it to the public to increase awareness of WNV. Thus, more preventive methods could be adopted during the peak WNV season and the locations most affected. Through this process, we strengthened our ability to search for suitable datasets using the web browser. We searched for accessible federal, state, and local public health data on WNV. That provided us with the opportunity to see how such data are organized and how plots and graphs are presented, which helped us decide on our own visual presentation. As an example, the plots and graphs on the government website (CDC) follow the guidelines for creating effective plots and graphs, such as using a clear, meaningful labels and providing useful references. Being able to see how the information we learned about in class is put into practice encouraged us to proceed with our own project in these same ways. 

## list out the major problems/bugs we encountered (including what the problem is, what methods we try to resolve it, and what we decide to do at the end) please add more
Throughout this project, we encountered several technical problems. In addition to seeking help from our instructor to resolve these issues, we also utilized the issues section on GitHub to update issues and problems we encountered so we could troubleshoot them as they occurred.

1. The first major problem we encountered dealt with inconsistent leaflet plot rendering. On one computer, the written code worked to render a plot of Illinois with county borders and county names as popups. Unfortunately, this map did not render properly on other computers. We had no solution to this problem for some time, and did plan to proceed with the creation of our app in hopes that the correct rendering would happen at a different stage of the project. Interestingly, our solution to this issue was revealed within the troubleshooting process of another issue. As we tried to fill polygons based on our demographic indicators, our spatial data output in incorrect locations. By properly ordering our demographic dataframe and our spatial information, this issue was solved and then our map output correctly on all computers.  

2.We used `leaflet()` function to create a map widget so that we can modify and add more features. We proceeded with `setView`, `addProviderTiles()`, and `addPolygons()` to set the center and zoom level of the map with added tile layers `OpenStreetMap` and county boundaries. However, the added polygon part was not printed correctly on all the collaborators' computers. We first shared that problem with the whole group, and attempted to troubleshoot a solution by considering different suggestions, including change to `sf` class (operate on spatial data) instead `ss`, restart RStudio, recheck the version of RStudio, re-download RStudio to the most updated version, 
We also consulted our instructors on this issue, a few more suggestions were given: google such issue in the R community, use `devtools` to list all packages in order to check the versions among the collaborators, ...
We need to get this issue resolved in order to proceed with Shiny app part of the project. 

3.Shiny App:

## The Challenges we have met
Additionally, our biggest challenge was to find the dataset that would allow us to gather all the epidemiological information in a format that is easy to navigate in R. We started with some of the large federal organizations, such as the Centers for Disease Control and Prevention (CDC); however, we were unable to find the source of the raw data to download. For example, the WNV data provided by the CDC were already presented in a map or a plot to show the incidents in a specific location, or the incidents were only depicted using one variable, such as age, which did not fit the goal of our project. Our instructor then suggested that we look at some state level and local level public health departments. Our initial aim was to find WNV epidemiological data for Larimar County in Colorado. However, we did not find any available raw data to retrieve. We did find WNV data for the state of Illinois, which contained information that we hoped to integrate into our map and app. In the end, that is the dataset we chose to use for this project. 
Another challenge we were facing was the absence of some of our team members due to other school-related commitments, tasks, and duties. In the beginning, it was a bit challenging in keep all the team members updated and to discuss the goals and plans we have for this project. However, we were able to handle that issue by delegating tasks to different people based on their availabilities and preferences. Team members who may be missing more classes towards the end of the project would help clean and explore the dataset to prepare it to merge with the map. At the same time, another member could start preparing to make the map of Illinois. People who missed classes at the beginning of the project would work on drafting the report and preparing the presentation. Because there are four people in our group, we came up with the idea that two of us would collaborate on designing the map. One person took on the challenge of designing the app, and one person was responsible for drafting the report and preparing the presentation. 

## add a short paragraph about "what we would do differently if we started fresh"
Overall, we really appreciated our instructors' suggestions; that input helped us capture all our thoughts and ideas, so we could better organize our project, and it helped us troubleshoot the problems we encountered as we worked on the project.  We also appreciate the constant helps and supports we had for each other.
