---
title: "Layering map"
author: "Nichole Monhait & Kathleen Wendt"
date: "11/28/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r global_options, echo = FALSE}
knitr::opts_chunk$set(fig.width=5, fig.height=4, fig.path='figs/',
                      warning=FALSE, message=FALSE, error=FALSE)
```


```{r load packages, echo = FALSE}

library(tidyverse)
library(tigris)
library(ggplot2)
library(ggthemes)
library(sf)
library(leaflet)
library(sp)
library(readr)

```


```{r read data, echo = FALSE}

il_wvn <- read_csv("../data/data_il.csv")

```


```{r join lat long with data}

data_il <- read_csv("../data/data_il.csv") %>%
  rename(NAME = il)

il_counties_2 <- il_counties %>%
  select(STATEFP, COUNTYFP, geometry, NAME)

full_il <- inner_join(data_il, il_counties, by = "NAME")

```


```{r bring in polygon info for IL}

# IL FIPS = 17
il_counties <- counties(state = "IL", cb = TRUE, class = "sf") %>% 
  st_set_crs(NA) %>%
  st_set_crs(4326)

il_skeleton <- il_counties %>% 
  ggplot() +
  geom_sf(data = il_counties) 

```


```{r switch sf to sp}

il_sp <- sf:::as_Spatial(il_counties)

```



```{r switch sf to sp in leaflet}

il <- leaflet(il_sp) %>%
  addPolygons() %>% 
  # setView(lng = -89.3985, lat = 40.6331, zoom = 8) %>% 
  addProviderTiles("OpenStreetMap.BlackAndWhite") # %>%  
  # addPolygons(color = "black", weight = 1, fillOpacity = 0)

il
```


```{r add leaflet}

il <- leaflet(il_counties) %>%
  setView(lng = -89.3985, lat = 40.6331, zoom = 8) %>% 
  addProviderTiles("OpenStreetMap.BlackAndWhite") %>%  
  addPolygons(color = "black", weight = 1, fillOpacity = 0)

il

```


