---
title: "Exploring demographic trends of West Nile human cases in Illinois"
author: "Nichole Monhait, Kathleen Wendt, Jessy Jiao, and Randy Xun"
date: "12/3/2018"
output:
  html_document:
    df_print: paged
---

```{r global_options, echo = FALSE}
knitr::opts_chunk$set(fig.width=5, fig.height=4, fig.path='figs/',
                      warning=FALSE, message=FALSE, error=FALSE)
```


```{r packages, echo = FALSE}

library(dplyr)
library(broom)
library(assertive)
library(tidyverse)
library(stringi)
library(stringr)
library(readr)
library(ggplot2)
library(gridExtra)
library(ggthemes)
library(dlnm)
library(pander)
library(tikzDevice)
library(packrat)
library(knitr)
library(xtable)
library(tinytex)
library(lubridate)
library(shiny)
library(kableExtra)
library(lubridate)
library(forcats)
library(devtools)
library(plotflow)
library(scales)
library(viridis)
```


```{r read and clean data}

il_wvn <- read_csv("../data/data_il.csv")

## Data will be made ready for pie charts
##This is so I can get the denominator
total_cases <- il_wvn %>% 
  summarize(cases = sum(count))

##This is for ethnicity comparison
race_count <- il_wvn %>% 
  filter(ethnicity %in% c("Hispanic or Latino", "NotHispNotLatino")) %>% 
  group_by(ethnicity) %>% 
  summarize(events = n(),
            cases = sum(count))

##This is for the age count
age_count <- il_wvn %>% 
  filter(agegroup != "na") %>% 
  group_by(agegroup) %>% 
  summarize(cases = sum(count))

##This is for the year
year_count <- il_wvn %>% 
  filter(year != "na") %>% 
  group_by(year) %>% 
  summarize(cases = sum(count))

##This is for state vs county
area_count <- il_wvn %>% 
  filter(stateorcounty != "na") %>% 
  group_by(stateorcounty) %>% 
  summarize(cases = sum(count))



```

```{r}
library(tidyverse)
library(tigris)
library(ggplot2)
library(ggthemes)
library(sf)
library(leaflet)
#bring in polgyon info for IL counties
#IL FIPS = 17
il_counties <- counties(state = "IL", cb = TRUE, class = "sf") %>% 
  st_set_crs(NA) %>% st_set_crs(4326)

il_skeleton <- il_counties %>% 
  ggplot() +
  geom_sf(data = il_counties) 


#leaflet package

il <- leaflet(il_counties) %>%
  setView(lng = -89.3985, lat = 40.6331, zoom = 8) %>% 
  addProviderTiles("OpenStreetMap.BlackAndWhite") %>%  
  addPolygons(color = "black", weight = 1, fillOpacity = 0)

il
```


